### ISSUE TITLE
ModuleNotFoundError: No module named 'promgen.manage'

### ISSUE THREAD

**Issue by jiaodou** [line/promgen#108]
HI developer：
   I install Promgen for a development environment
python3 -m venv /path/to/virtualenv --ok
source /path/to/virtualenv/bin/activate --ok
pip install -e ./tmp/promgen --ok
pip install mysqlclient --ok
promgen bootstrap --error

(virtualenv) [root@python-rh7 tmp]# promgen bootstrap
Traceback (most recent call last):
  File "/path/to/virtualenv/bin/promgen", line 11, in <module>
    load_entry_point('promgen', 'console_scripts', 'promgen')()
  File "/path/to/virtualenv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/path/to/virtualenv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/path/to/virtualenv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/path/to/virtualenv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'promgen.manage'

**Comment by jiaodou** [comment]
Uzip lost some files. It's my fault.
and I run pip install -e ./tmp/promgen , lost manage.py, so...

then,
I run pip uninstall promgen, --ok
run pip install -e ./tmp/promgen --ok
But it's still lost some files, it lost 
/path/to/virtualenv/lib/python3.6/site-packages/promgen/tests/examples
 and 
/path/to/virtualenv/lib/python3.6/site-packages/promgen/tests/notifications,
I don't know why..

**Comment by jiaodou** [comment]
I copy examples and notifications, and
promgen bootstrap --ok
echo 1 > ~/.config/promgen/DEBUG --ok
promgen migrate --ok
promgen test --error


[root@python-rh7 bin]# promgen test
Traceback (most recent call last):
  File "/path/to/virtualenv/bin/promgen", line 11, in <module>
    load_entry_point('promgen==0.31.dev0', 'console_scripts', 'promgen')()
  File "/path/to/virtualenv/lib64/python3.6/site-packages/promgen/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/path/to/virtualenv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/path/to/virtualenv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/path/to/virtualenv/lib64/python3.6/site-packages/django/core/management/commands/test.py", line 26, in run_from_argv
    super().run_from_argv(argv)
  File "/path/to/virtualenv/lib64/python3.6/site-packages/django/core/management/base.py", line 308, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/path/to/virtualenv/lib64/python3.6/site-packages/django/core/management/base.py", line 282, in create_parser
    self.add_arguments(parser)
  File "/path/to/virtualenv/lib64/python3.6/site-packages/django/core/management/commands/test.py", line 47, in add_arguments
    test_runner_class = get_runner(settings, self.test_runner)
  File "/path/to/virtualenv/lib64/python3.6/site-packages/django/test/utils.py", line 308, in get_runner
    test_module = __import__(test_module_name, {}, {}, test_path[-1])
ModuleNotFoundError: No module named 'django_nose'

**Comment by kfdm** [comment]
> No such file or directory: '/usr/local/bin/promtool

Promgen needs to know the path to promtool so that it can check to see if the rules file is valid before outputing it. This can be configured in promgen.yaml

> ModuleNotFoundError: No module named 'django_nose'

To run tests you'll need to install Promgen with the optional test requirements `pip install -e .[dev]` should work.

As for the lost files, I will try to take a look this week though I'm out of office for most of today.

**Comment by jiaodou** [comment]
Promgen  192.168.99.100，
prometheus 172.24.148.164
I can't find file ‘promtool’ on 192.168.99.100,
Must I  intall Promgen on 172.24.148.164 with prometheus ?

**Comment by kfdm** [comment]
Part of that is likely a problem with the documentation. I will try to fix that. In the meantime as reference you can see for the docker image, we download a promtool binary so that Promgen can use it directly to confirm the rule syntax

https://github.com/line/promgen/blob/78ece8167f065169d12f85778fe77a03d8c15a58/Dockerfile#L11-L16

In a similar way, using your preferred deployment tool, download a recent Prometheus release and copy promtool into a location that Promgen can access.

**Comment by jiaodou** [comment]
Thank you for your answer.
I copy this file from prometheus(172.24.148.164),  this problem has been solved.
But have new problem:
When I chick Register Rule button, the page is loading forever, not jump next page.
Mysql table:promgen_rule have a new record which I create on page.
install with docker did not have this problem.

**Comment by jiaodou** [comment]
This will happen if you use code:  ‘return self.form_invalid(form)’ in views.py .
This only happen in 'install Promgen for a development environment', not happen in 'install with docker'.

**Comment by jiaodou** [comment]
self.form_invalid(form) 
is
<HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/rule/2/edit">
but no jump.

**Comment by jiaodou** [comment]
Thank you for your answer.
I copy this file from prometheus(172.24.148.164), this problem has been solved.
But have new problem:
When I chick Register Rule button, the page is loading forever, not jump next page.
Mysql table:promgen_rule have a new record which I create on page.
install with docker did not have this problem.

This will happen if you use code: ‘return self.form_invalid(form)’ in views.py .

self.form_invalid(form)
is
<HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/rule/2/edit">

install Promgen for a development environment --no jump
install with docker --jump

**Comment by kfdm** [comment]
Hmm. I'm a little confused why it would be getting stuck with development environment but not docker (usually docker is the difficult one to debug)

Can you verify that promtool is executable ?  `promtool --version`

If promtool is in a different location, you may need to edit `~/.config/promgen/promgen.yml` to ensure that Promgen can locate promtool

```yaml
prometheus:
  # Path to promtool to verify valid rules file
  promtool: /usr/local/bin/promtool
```

**Comment by jiaodou** [comment]
[root@i-F7D45611 bin]# /usr/local/bin/promtool --version
promtool, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2

promgen.yml
  promtool: /usr/local/bin/promtool

**Comment by kfdm** [comment]
Can you post the clause (the Prometheus query part) of the rule you are trying to save?
I'm still a little confused why the docker version would work but the development version would not.
Also could you tell me which file you are downloading Promgen from?

**Comment by jiaodou** [comment]
development version 3.1dev(master)
docker version 3.0
That's the reason.
I switch to  version 3.0 on development, it's work.

**Comment by jiaodou** [comment]
The real reason is :
    admin--Promgen › Shards › Default --Prometheis--add Host:172.24.148.164 Port:9090
I delete this host, it's work.
add host,it would not.
You can test.

**Comment by kfdm** [comment]
Have you configured `CELERY_BROKER_URL` ?
Adding or removing a Prometheus server should not make a difference, but if no `CELERY_BROKER_URL` is configured, then it could be getting stuck there.

**Comment by jiaodou** [comment]
Thank you for your answer.
I configured CELERY_BROKER_URL, redis maybe have problems.
There have new problem with gunicorn:
pip install gunicorn --ok,
gunicorn promgen.wsgi:application -w 4 -b 0.0.0.0:8000 --ok
When I visit  ip:8000,
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/promgen.css
Not Found: /static/css/bootstrap-switch.min.css
Not Found: /static/js/jquery.min.js
Not Found: /static/css/bootstrap-theme.min.css
Not Found: /static/css/bootstrap-datetimepicker.min.css
Not Found: /static/js/jquery.selection.js
Not Found: /static/js/moment.min.js
Not Found: /static/js/bootstrap3-typeahead.min.js
Not Found: /static/js/bootstrap.min.js
Not Found: /static/js/bootstrap-datetimepicker.min.js
Not Found: /static/js/bootstrap-switch.min.js
Not Found: /static/js/promgen.js
Not Found: /static/js/bootstrap3-typeahead.min.js
Not Found: /static/js/moment.min.js
Not Found: /static/js/bootstrap-datetimepicker.min.js
Not Found: /static/js/bootstrap-switch.min.js
Not Found: /static/js/promgen.js

Can you tell me which step is wrong?
Or I lost some steps?

**Comment by jiaodou** [comment]
I run SECRET_KEY=1 promgen collectstatic:
'''
Copying '/path/to/virtualenv/lib64/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.js'
Copying '/path/to/virtualenv/lib64/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.min.js'
Copying '/usr/src/app/promgen/static/css/bootstrap-datetimepicker-standalone.css'
Copying '/usr/src/app/promgen/static/css/bootstrap-datetimepicker.min.css'
Copying '/usr/src/app/promgen/static/css/bootstrap-switch.min.css'
Copying '/usr/src/app/promgen/static/css/bootstrap-theme.min.css'
Copying '/usr/src/app/promgen/static/css/bootstrap-theme.min.css.map'
Copying '/usr/src/app/promgen/static/css/bootstrap.min.css'
Copying '/usr/src/app/promgen/static/css/bootstrap.min.css.map'
Copying '/usr/src/app/promgen/static/css/promgen.css'
Copying '/usr/src/app/promgen/static/fonts/glyphicons-halflings-regular.eot'
Copying '/usr/src/app/promgen/static/fonts/glyphicons-halflings-regular.svg'
Copying '/usr/src/app/promgen/static/fonts/glyphicons-halflings-regular.ttf'
Copying '/usr/src/app/promgen/static/fonts/glyphicons-halflings-regular.woff'
Copying '/usr/src/app/promgen/static/fonts/glyphicons-halflings-regular.woff2'
Copying '/usr/src/app/promgen/static/js/bootstrap-datetimepicker.min.js'
Copying '/usr/src/app/promgen/static/js/bootstrap-switch.min.js'
Copying '/usr/src/app/promgen/static/js/bootstrap.min.js'
Copying '/usr/src/app/promgen/static/js/bootstrap3-typeahead.min.js'
Copying '/usr/src/app/promgen/static/js/jquery.min.js'
Copying '/usr/src/app/promgen/static/js/jquery.selection.js'
Copying '/usr/src/app/promgen/static/js/locales.min.js'
Copying '/usr/src/app/promgen/static/js/moment-with-locales.min.js'
Copying '/usr/src/app/promgen/static/js/moment.min.js'
Copying '/usr/src/app/promgen/static/js/promgen.js'

141 static files copied to '/root/.cache/promgen'.

(virtualenv) [root@i-AE133268 app]# cd /root/.cache/promgen/
(virtualenv) [root@i-AE133268 promgen]# ll
total 12
drwxr-xr-x 6 root root   47 Nov 14 14:32 admin
drwxr-xr-x 2 root root 4096 Nov 14 14:32 css
drwxr-xr-x 2 root root 4096 Nov 14 14:32 fonts
drwxr-xr-x 2 root root 4096 Nov 14 14:32 js



It's still has no work.

**Comment by jiaodou** [comment]
Is whitenoise version， docker is 3.3.1 ,development environment is 4.1.1，I switch to  3.3.1 ，is't work.
