### ISSUE TITLE
docker v0.31 v0.32-dev not work well

### ISSUE THREAD

**Issue by or0or1** [line/promgen#117]
@kfdm 

so long not see. haha

docker pull  line/promgen:v0.31 
docker pull line/promgen:master
docker pull line/promgen:latest

do not work well.

visit /static/*.css   404

**Comment by kfdm** [comment]
Thank you for the report. I wonder if this happened from upgrading some dependencies when I switched to Pipfile for development. I will take a look and see if I can get a fix out :)
