### ISSUE TITLE
Initial setup issues - createsuperuser and celery

### ISSUE THREAD

**Issue by jfreeland** [line/promgen#134]
I was trying to get up and running to do some testing and ran into some issues.  I started with:

joey@mbp : ~/Desktop/projects/promgen > docker-compose up -d
...
Creating promgen_redis_1    ... done                                                                                                                
Creating promgen_blackbox_1 ... done                                                                                                              
Creating promgen_base_1     ... done                                                                                                             
Creating promgen_mysql_1    ... done                                                                                                                                                     
Creating promgen_web_1      ... done                                                                                                                              
Creating promgen_alertmanager_1 ... done                                                                                                               
Creating promgen_prometheus_1   ... done                                                                                                                                                 
Creating promgen_worker_1       ... done

docker-compose run web createsuperuser

joey@mbp : ~/Desktop/projects/promgen > docker-compose run web createsuperuser                                                
                                                                                        
Starting promgen_redis_1 ... done                                                                                            
Starting promgen_mysql_1 ... done

You have 34 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, authtoken, contenttypes, promgen, sessions, sites, social_django.                                                                                  
Run 'python manage.py migrate' to apply them.
...
django.db.utils.ProgrammingError: (1146, "Table 'promgen.auth_user' doesn't exist")

I logged into the promgen_web_1 container and attempted to run manage.py migrate, but I ran into other issues, most notably that it was getting stuck importing celery because it appears to be importing https://github.com/line/promgen/blob/master/promgen/celery.py rather than the celery library.

**Comment by kfdm** [comment]
This is probably a documentation mistake on my part (I have not updated the documentation in a while). Could you try running this command

`docker-compose run web docker-compose-bootstrap` which should create the database and then you can run `docker-compose run web createsuperuser`

You could also run the migration by itself and then createsuperuser and it should work

```
docker-compose run migrate
docker-compose run createsuperuser
```

**Comment by jfreeland** [comment]
That did the trick.  Thanks!
