### ISSUE TITLE
How to create promgen.json file?

### ISSUE THREAD

**Issue by momoco530** [line/promgen#138]
hill, i run promgen by docker,and the project running seems normally.but do not know how to create the promgen.json

**Comment by kfdm** [comment]
`promgen.json` is generated from Promgen when you save changes (add a new exporter, delete a host, or anything else that affects your monitoring targets). Typically the Promgen worker would run next to Prometheus (on the same server or as a container with a shared volume) so that Promgen can write a promgen.json file that Prometheus can then read.

There are docs here ( https://promgen.readthedocs.io/en/latest/conf/index.html ) but it's possible there are parts that are difficult to understand.

**Comment by momoco530** [comment]
promgen.json was not generated from Promgen when i save changes
    [2019-03-18 15:38:49 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:9)
    [2019-03-18 07:38:49 +0000] [9] [INFO] Worker exiting (pid: 9)

**Comment by momoco530** [comment]
Is it related to time zone?

**Comment by kfdm** [comment]
Hmm. Timezone settings should not have anything to do with it.
Are you running with `docker` directly or are you using `docker-compose`? I think I would need to know a little more about how it is configured, and more logs from the worker, to understand where the problem might be.

**Comment by momoco530** [comment]
I'm running with docker
promgen.yml
  prometheus:
    url: http://192.168.137.128:9090/
    version: 2
    promtool: /usr/local/bin/promtool
    rules: /etc/prometheus/promgen.rule.yml

  alertmanager:
    url: http://alertmanager:9093

  alert_blacklist:
    severity: ["debug", "blackhole"]

  config_writer:
    path: /etc/prometheus/promgen.json

  url_writer:
    path: /etc/prometheus/blackbox.json

**Comment by momoco530** [comment]
celery worker logs
 -------------- celery@b5e0c5e95264 v4.1.1 (latentcall)
---- **** ----- 
--- * ***  * -- Linux-3.10.0-327.el7.x86_64-x86_64-with 2019-03-18 09:26:46
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         promgen:0x7f2a591829e8
- ** ---------- .> transport:   redis://192.168.137.128:6380/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 24 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> b5e0c5e95264     exchange=(direct) key=b5e0c5e95264
                .> celery           exchange=celery(direct) key=celery

[2019-03-18 09:26:48,985: WARNING/ForkPoolWorker-14] Request: <Context: {'lang': 'py', 'task': 'promgen.celery.debug_task', 'id': 'd86dc6f4-6fae-4af9-a038-e07ec6b5dd71', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'd86dc6f4-6fae-4af9-a038-e07ec6b5dd71', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@b5e0c5e95264', 'reply_to': '95d08a4a-87a5-33a6-8939-fdef1f5532de', 'correlation_id': 'd86dc6f4-6fae-4af9-a038-e07ec6b5dd71', 'delivery_info': {'exchange': '', 'routing_key': 'b5e0c5e95264', 'priority': 0, 'redelivered': None}, 'args': [], 'kwargs': {}, 'hostname': 'celery@b5e0c5e95264', 'is_eager': False, 'callbacks': None, 'errbacks': None, 'chain': None, 'chord': None, 'called_directly': False, '_protected': 1}>

**Comment by kfdm** [comment]
Can you look over the instructions here ?

https://promgen.readthedocs.io/en/latest/conf/prometheus.html

Judging by the celery output, it's only listening to the default queue `celery` but not listing to any specific Prometheus queue. Promgen writes to each Prometheus server's queue when it triggers a configuration change.

```
docker run --rm \
    -v ~/.config/promgen:/etc/promgen/ \
    -v /etc/prometheus:/etc/prometheus \
    line/promgen worker -l info --queues prometheus001
```

would tell the worker to listen to the queue for our server prometheus001

**Comment by momoco530** [comment]
Thanks very much

**Comment by liuzh-sa** [comment]
> Can you look over the instructions here ?
> 
> https://promgen.readthedocs.io/en/latest/conf/prometheus.html
> 
> Judging by the celery output, it's only listening to the default queue `celery` but not listing to any specific Prometheus queue. Promgen writes to each Prometheus server's queue when it triggers a configuration change.
> 
> ```
> docker run --rm \
>     -v ~/.config/promgen:/etc/promgen/ \
>     -v /etc/prometheus:/etc/prometheus \
>     line/promgen worker -l info --queues prometheus001
> ```
> 
> would tell the worker to listen to the queue for our server prometheus001

Hi Paul, is "prometheus001" a fixed name or the hostname of the prometheus server?

**Comment by momoco530** [comment]
Hi
    
    I use the Prometheus server IP



momoco530@sina.com
 
From: liuzh-sa
Date: 2021-01-15 15:57
To: line/promgen
CC: momoco530; State change
Subject: Re: [line/promgen] How to create promgen.json file? (#138)
Can you look over the instructions here ?
https://promgen.readthedocs.io/en/latest/conf/prometheus.html
Judging by the celery output, it's only listening to the default queue celery but not listing to any specific Prometheus queue. Promgen writes to each Prometheus server's queue when it triggers a configuration change.
docker run --rm \
    -v ~/.config/promgen:/etc/promgen/ \
    -v /etc/prometheus:/etc/prometheus \
    line/promgen worker -l info --queues prometheus001

would tell the worker to listen to the queue for our server prometheus001
Hi Paul, is "prometheus001" a fixed name or the hostname of the prometheus server?

**Comment by liuzh-sa** [comment]
> Hi I use the Prometheus server IP momoco530@sina.com From: liuzh-sa Date: 2021-01-15 15:57 To: line/promgen CC: momoco530; State change Subject: Re: [line/promgen] How to create promgen.json file? (#138) Can you look over the instructions here ? https://promgen.readthedocs.io/en/latest/conf/prometheus.html Judging by the celery output, it's only listening to the default queue celery but not listing to any specific Prometheus queue. Promgen writes to each Prometheus server's queue when it triggers a configuration change. docker run --rm \ -v ~/.config/promgen:/etc/promgen/ \ -v /etc/prometheus:/etc/prometheus \ line/promgen worker -l info --queues prometheus001 would tell the worker to listen to the queue for our server prometheus001 Hi Paul, is "prometheus001" a fixed name or the hostname of the prometheus server? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

HI,i ran promgen by docker as follows：
sudo docker run --rm -d -p 8000:8000 -v /etc/promgen/:/etc/promgen/ -e DEBUG=1 -e ALLOWED_HOSTS=* 10.200.10.11:5000/line/promgen
sudo docker run --rm -d -v /etc/promgen/:/etc/promgen/ -v /etc/prometheus:/etc/prometheus 10.200.10.11:5000/line/promgen worker --queues prometheus001  -l debug


I added rules, but no configuration file was generated on the backend server "/etc/prometheus/"

**Comment by liuzh-sa** [comment]
> > Hi I use the Prometheus server IP [momoco530@sina.com](mailto:momoco530@sina.com) From: liuzh-sa Date: 2021-01-15 15:57 To: line/promgen CC: momoco530; State change Subject: Re: [line/promgen] How to create promgen.json file? (#138) Can you look over the instructions here ? https://promgen.readthedocs.io/en/latest/conf/prometheus.html Judging by the celery output, it's only listening to the default queue celery but not listing to any specific Prometheus queue. Promgen writes to each Prometheus server's queue when it triggers a configuration change. docker run --rm \ -v ~/.config/promgen:/etc/promgen/ \ -v /etc/prometheus:/etc/prometheus \ line/promgen worker -l info --queues prometheus001 would tell the worker to listen to the queue for our server prometheus001 Hi Paul, is "prometheus001" a fixed name or the hostname of the prometheus server? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> HI,i ran promgen by docker as follows：
> sudo docker run --rm -d -p 8000:8000 -v /etc/promgen/:/etc/promgen/ -e DEBUG=1 -e ALLOWED_HOSTS=* 10.200.10.11:5000/line/promgen
> sudo docker run --rm -d -v /etc/promgen/:/etc/promgen/ -v /etc/prometheus:/etc/prometheus 10.200.10.11:5000/line/promgen worker --queues prometheus001 -l debug
> 
> I added rules, but no configuration file was generated on the backend server "/etc/prometheus/"

Hi，momoco，can you show your configuration as follows：
prometheus.yml  promgen.yml  alertmanager.yml
