### ISSUE TITLE
Unable to configure promgen in a VM environment

### ISSUE THREAD

**Issue by sumanpatra** [line/promgen#146]
@kfdm 

I am trying to setup promgen for our prometheus environment, however I am unable to find out a standard procedure about installing and configuring promgen.

I have downloaded the code https://github.com/line/promgen/archive/master.zip and can start promgen in a python venv by running "#promgen runserver" but unable to understand how I am going to deploy worker in each prometheus server and start promgen worker and integrate the same with promgen web running in promgen:8000.

I am very much interested to deploy promgen and running it, so any help will be highly appreciated.

Thanks & regards,
Suman

**Comment by kfdm** [comment]
While some of the docs are a bit light, I think I have most of the basics documented here
https://promgen.readthedocs.io/en/latest/conf/index.html 

For example, some of the worker configuration is explained here
https://promgen.readthedocs.io/en/latest/conf/prometheus.html

Is there something that is still unclear?

**Comment by sumanpatra** [comment]
Yes I have already gone through these two links before reaching out, architecture is great but somewhere I am looking for "Deployment Architecture"
I believe somewhere I am missing something or I am doing completely wrong way. Here are the details what I am doing


##On Promgen Server##
(venv) root@promgentest:~# promgen runserver &
[1] 2539
(venv) root@promgentest:~# /root/promgen/promgen/settings.py:249: UserWarning: Unset SECRET_KEY setting to random for now
  warnings.warn('Unset SECRET_KEY setting to random for now')
/root/promgen/promgen/settings.py:249: UserWarning: Unset SECRET_KEY setting to random for now
  warnings.warn('Unset SECRET_KEY setting to random for now')
Performing system checks...

System check identified no issues (0 silenced).
May 17, 2019 - 02:55:32
Django version 2.1.8, using settings 'promgen.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

(venv) root@promgen:~# promgen register promgentest prometheus001 9090


##on each prometheus server##

Question: Do I need to use above steps again and point the DATABASE_URL & CELERY_BROKER_URL to the same as above promgen server?

How to start promgen worker in  each prometheus server?

(venv) root@prometheus1:~# celery worker -A promgentest -l info --queues prometheus1

**Comment by kfdm** [comment]
After generating the configuration, you should be able to copy the same values to the Prometheus workers (everything in ~/.config/promgen)

In my case, I tend to deploy things using Saltstack, but something like Ansible or any other configuration management should also work.

**Comment by sumanpatra** [comment]
Thanks will do the same. To start worker is it the same command I need to run on each prometheus server?

(venv) root@prometheus1:~# celery worker -A promgentest -l info --queues prometheus1

**Comment by kfdm** [comment]
That should be correct. I will also see if I can make that more clear in the installation docs.

**Comment by sumanpatra** [comment]
Thanks Paul.

Yes I have tried the same way.

It will be really good if we have a clear installations docs for individual VM along with components which need to pre-install on all VMs to make this work.
