### ISSUE TITLE
Bootstrapping Promgen 

### ISSUE THREAD

**Issue by alexg84** [line/promgen#159]
Hi,
I made a mistake in the configuration, I removed the docker deleted the image and cler all the docker cache, but when im running this command again, I receiving that SECRET_KEY , DATABASE_URL , CELERY_BROKER_URL are exists.
how can I change these parameters

please advise  

ubuntu@prometheus:~$ docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen bootstrap
Bootstrapping Promgen
  Setting SECRET_KEY exists
  Setting DATABASE_URL exists
  Setting CELERY_BROKER_URL exists

**Comment by tuan-phan** [comment]
@alexg84 Please modify these of file in **~/.config/promgen**

**Comment by kfdm** [comment]
Sorry for the late reply! thuan-phan is correct. You should be able to modify the files in `~/.config/promgen`

**Comment by alexg84** [comment]
thank you for the help, in order to use promgen, I have to install MySQL and Redis in my localhost?

**Comment by tuan-phan** [comment]
Yeah. You can use **docker-compose up** install Redis, MySql, Prometheus, Celery, Alert Manager as well.

**Comment by alexg84** [comment]
Hi tuan-phan,
Thank you for your help.  
I have Prometheus and alert manager installed already so I understand that I need MySQL and Redis what about Celery?  is It must 
thank you in advance

**Comment by alexg84** [comment]
Thank you for an answer, I tried to use docker-compose but  some of the containers doesn't start
ubuntu@ip-10-10-10-66:~/promgen$ docker-compose ps
         Name                       Command               State            Ports
-----------------------------------------------------------------------------------------
promgen_alertmanager_1   /bin/alertmanager -config. ...         Exit 1
promgen_base_1                 /docker-entrypoint.sh dock ...        Exit 1
promgen_blackbox_1         /bin/blackbox_exporter --c ...          Up       9115/tcp
promgen_mysql_1             docker-entrypoint.sh mysqld            Up       3306/tcp, 33060/tcp
promgen_prometheus_1     /bin/prometheus --config.f ...        Exit 1
promgen_redis_1             docker-entrypoint.sh redis ...             Up       6379/tcp
promgen_web_1              /docker-entrypoint.sh prom ...             Up       0.0.0.0:8080->8000/tcp
promgen_worker_1         /docker-entrypoint.sh work ...              Up       8000/tcp

**Comment by tuan-phan** [comment]
Hmm I'm not sure about your prometheus container. Anyway you can fix the alertmanager container by change this command in https://github.com/line/promgen/blob/master/docker-compose.yml#L55
`--config.file=/etc/prometheus/alertmanager.yml` is correct in this case
