### ISSUE TITLE
Cannot use TestQuery function

### ISSUE THREAD

**Issue by tuan-phan** [line/promgen#161]
Hi Team,
I tried to install Promgen via docker-compose and manual as well. Anyway, In both of way, I can not use TestQuery function.
It always show 
`jquery.min.js:4 POST http://127.0.0.1:8080/rule/0/test 500 (Internal Server Error)`
![Screen Shot 2019-08-02 at 15 33 44](https://user-images.githubusercontent.com/29539892/62349537-000c1300-b53b-11e9-8011-86290e8c724d.png)

Log file from docker-compose

```
> web_1           | [02/Aug/2019 06:25:32] "POST /rule/0/test HTTP/1.1" 500 16836
web_1           | Internal Server Error: /rule/0/test
web_1           | Traceback (most recent call last):
web_1           |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1           |     response = get_response(request)
web_1           |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1           |     response = self.process_exception_by_middleware(e, request)
web_1           |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1           |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1           |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1           |     return view_func(*args, **kwargs)
web_1           |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
web_1           |     return self.dispatch(request, *args, **kwargs)
web_1           |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
web_1           |     return super().dispatch(request, *args, **kwargs)
web_1           |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
web_1           |     return handler(request, *args, **kwargs)
web_1           |   File "/usr/src/app/promgen/views.py", line 1241, in post
web_1           |     result = util.get(url, {'query': query}).json()
web_1           |   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
web_1           |     return complexjson.loads(self.text, **kwargs)
web_1           |   File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
web_1           |     return _default_decoder.decode(s)
web_1           |   File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
web_1           |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
web_1           |   File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
web_1           |     raise JSONDecodeError("Expecting value", s, err.value) from None
web_1           | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
```

Can you have a look?
Thank you
CC: @kfdm

**Comment by kfdm** [comment]
Hmm. I have not tested extensively in docker, so I'm not certain. It may be next week before I'm able to test, but in the past, some of my assumptions about docker-networking were probably a little bit off. It looks like perhaps it's unable to query the upstream Prometheus container, so is failing with a JSONDecodeError.

Just to confirm, if you go to the shards page ( http://localhost:8000/shard/ ) are there any shards registered ?

**Comment by tuan-phan** [comment]
Hi @kfdm ,
I confirmed that I have one shard with prometheus server working correctly.
![Screen Shot 2019-08-02 at 16 08 08](https://user-images.githubusercontent.com/29539892/62353321-6138e400-b545-11e9-857d-8c78372d42a8.png)
![Screen Shot 2019-08-02 at 16 18 00](https://user-images.githubusercontent.com/29539892/62353372-7d3c8580-b545-11e9-95db-2349005fbf0d.png)

I already deploy one server from source code. And I still get 500 exit code error when I try to test the query
![Screen Shot 2019-08-02 at 16 47 26](https://user-images.githubusercontent.com/29539892/62353341-69911f00-b545-11e9-8fb7-5efb0b612c9b.png)
I can register the new rule without testQuery
![Screen Shot 2019-08-02 at 16 45 39](https://user-images.githubusercontent.com/29539892/62353391-87f71a80-b545-11e9-9c91-5ecc851fd057.png)
Result in Prometheus server:
![Screen Shot 2019-08-02 at 16 45 58](https://user-images.githubusercontent.com/29539892/62353412-95140980-b545-11e9-8174-d9efc41ca5e4.png)
Query result in this Prometheus:
![Screen Shot 2019-08-02 at 16 46 20](https://user-images.githubusercontent.com/29539892/62353435-a0673500-b545-11e9-9aac-6b06dc1d1697.png)

Can you explain to me how TestQuery function work?
Thank you

**Comment by kfdm** [comment]
1. Posts to `/rule/0/test` (or `/rule/<id>test` for an existing rule) to get the meta data needed to test
2. With the rule formatted, it posts to Promgen's `/api/v1/query` endpoint proxy
3. which posts to each configured Prometheus server's `/api/v1/query` endpoint 
4. before collecting the result and returning it back

Seems like Promgen's proxy endpoint is not working correctly so perhaps you could try the query

`http://localhost:8000/api/v1/query?query=prometheus_build_info` and see what is returned ?

**Comment by tuan-phan** [comment]
Thank you @kfdm , I will test this command and response later.

**Comment by tuan-phan** [comment]
@kfdm 

> [prometheus@dev-systrdemo301z ~]$ curl http://localhost:8000/api/v1/query?query=prometheus_build_info | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   423  100   423    0     0   8913      0 --:--:-- --:--:-- --:--:--  9613
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "prometheus_build_info",
          "app_team_name": "trv_dm",
          "branch": "HEAD",
          "goversion": "go1.10.3",
          "host_group": "dev-mon-trprom1",
          "instance": "dev-mon-trprom101z.dev.jp.local:9090",
          "job": "prometheus",
          "platform": "riaas",
          "revision": "c305ffaa092e94e9d2dbbddf8226c4813b1190a0",
          "version": "2.4.2"
        },
        "value": [
          1564983013.334,
          "1"
        ]
      }
    ]
  }
}

I think the endpoint is OK. Anyway I still get 
`[05/Aug/2019 05:30:59] "POST /rule/0/test HTTP/1.1" 500 7295`

**Comment by kfdm** [comment]
Can you try putting Promgen in DEBUG mode by setting the environment var DEBUG=1 and see what the query returns via the Firefox/Chrome inspector ?

I'm still not seeing an error when I test locally in my environment.

**Comment by tuan-phan** [comment]
Yeah. I will do it now.

**Comment by tuan-phan** [comment]
@kfdm 
`Internal Server Error: /rule/0/test
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2a43499a58>: Failed to establish a new connection: [Errno 110] Connection timed out`
Hmm I don't know why but I can use curl directry from this server but via Promgen website it's fail...

**Comment by tuan-phan** [comment]
OMG
`HTTPConnectionPool(host='example.com', port=80)` I think I should have some Django setting here

**Comment by kfdm** [comment]
Hmm. Can you check the settings here? http://localhost:8000/admin/sites/site/

**Comment by tuan-phan** [comment]
Yeah. I can access this page and only site www.example.com is available. Unfortunately, I accidentally to delete this site and now I can't connect to promgen. 
![Screen Shot 2019-08-05 at 15 08 12](https://user-images.githubusercontent.com/29539892/62442447-ed8c1680-b792-11e9-9e4f-789863513a22.png)

**Comment by kfdm** [comment]
If you can connect to your database, you could try running a query like this

`INSERT INTO `django_site` VALUES (1, 'domain.name', 'Some friendly label')`

**Comment by tuan-phan** [comment]
Thank you so much @kfdm its work correctly. Issue close. Anyway, I have a question about import rules. Can I open the new issue?

**Comment by kfdm** [comment]
Sure, feel free to open a new issue if this particular one is resolved :)

**Comment by taiyang-li** [comment]
@tuan-phan I met the same problem with you previously, can you tell how you update the django admin site?
