### ISSUE TITLE
Testing rule failed (404 return) when I creating new rule

### ISSUE THREAD

**Issue by tuan-phan** [line/promgen#177]
Hi team,
I upgrade the latest Promgen and do some test here. When I creating the new rule and run test rule here. The result is 404 not found.

> [05/Sep/2019 07:27:45] "GET /proxy/v1/alerts HTTP/1.1" 200 53892
> [05/Sep/2019 07:27:45] "GET /proxy/v1/silences HTTP/1.1" 200 3079
> Not Found: /rule/0/test
> [05/Sep/2019 07:27:48] "POST /rule/0/test HTTP/1.1" 404 1759

Can you have a look?
It not happened in the old rule.

**Comment by kfdm** [comment]
I believe I see the bug. In #167 I was trying to cleanup some old code and upgrade to newer Django functions. Though I upgraded the route `path('rule/<int:pk>/test'` I failed to update the check to use an integer.  Let me test a fix and push a new version.

**Comment by tuan-phan** [comment]
Thank you for your action
