### ISSUE TITLE
[Question] How to manage and update promgen rule as code?

### ISSUE THREAD

**Issue by tuan-phan** [line/promgen#179]
If I'm correct, Promgen use database to store the rule and configuration. So if we want to manage promgen rule as code it's impossible.
Please advice me in this case @kfdm 
Thank you so much,

**Comment by kfdm** [comment]
Correct. Promgen manages its rules in the database, though there is a simple audit log for changes http://localhost:8000/audit (though its in need of serious improvement)

What I do for our infrastructure here, is I have a rule file managed by Promgen and one managed by my deployment pipeline (git)

Prometheus has no problems reading from multiple rule files

```
rule_files:
- /path/to/git.rule.yml
- /path/to/promgen.rule.yml
```

What kind of ideas did you have in mind, for managing rules as code ?

**Comment by tuan-phan** [comment]
Hmm I don't have any idea in this case. Seems like we should update code manual on Promgen UI if we want to modify something.
Thank you for your clarification!
