### ISSUE TITLE
support for ec2_sd_config and import lables from ec2_metadata

### ISSUE THREAD

**Issue by chitender** [line/promgen#190]
Hello,

we recently started using the promgen to manage the configuration for Prometheus and Alertmanager. for our use case we monitor 500+ AWS EC2 instances in our AWS account.

in our current deployment we use ec2_sd_config to discover the new EC2 instances and with ec2_metadata we categorise the instances.

we do not see any option in promgen through which we can leverage the ec2_sd_config service discovery.

if there is already a feature in promgen then do let us know.

**Comment by kfdm** [comment]
Prometheus has [ec2_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config) built in, so how were you expecting to use it in Promgen?
Promgen was built to bridge systems that did not have Prometheus support, and convert them to [file_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config)

It's possible to use ec2_sd_config directly in Prometheus, but use Promgen only for Alert rules and notification.
