### ISSUE TITLE
The alertmanger send notifys results 403

### ISSUE THREAD

**Issue by sundy-li** [line/promgen#205]
From the alertmanager log, it shows 403 when sending notify to Promgen.

```shell
level=error ts=2019-12-08T09:57:48.364Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 403: http://172.24.72.111:8082/alert"
```

**Comment by sundy-li** [comment]
My promgen web is `http://172.24.72.111:8082/`.

I guess there must be a url router for promgen to accept request to save the alerts for alertworker (No CSRF, No cookie needed)

**Comment by kfdm** [comment]
Sorry for the confusion
`/alert` is an older route that has been removed, the correct route is `/api/v1/alerts`
I will update the incorrect documentation

**Comment by sundy-li** [comment]
The '/api/v1/alerts' seems to be a proxy api to fetch the alert from alertmanager.

I think the promgen must have a route which   alertmanager can push alerts to save to the db.
So that the alert worker could consume and notify.

**Comment by sundy-li** [comment]
![image](https://user-images.githubusercontent.com/3325189/70398860-72957e00-1a5a-11ea-8520-89cbcf3035f9.png)

I can read the alert from web-ui, but I can't receive any notification.

**Comment by kfdm** [comment]
`/proxy/v1/alerts` is used for the Alertmanager route

```python
# Alertmanager Proxy
# Promgen does not pretend to be an Alertmanager so these can be slightly different
path("proxy/v1/alerts", csrf_exempt(proxy.ProxyAlerts.as_view()), name="proxy-alerts"),
```

```python
# Promgen API
path('api/v1/alerts', csrf_exempt(views.Alert.as_view()), name='alert'),
```

though I do want to do a bit of refactoring in the near future to better distinguish the Prometheus/Alertmanager proxy from the Promgen APIs

**Comment by sundy-li** [comment]
I am new to Django, but I figure out that now, thank you very much.
