### ISSUE TITLE
Hope to provide more documentation

### ISSUE THREAD

**Issue by peixiaoqing** [line/promgen#227]
Thanks for looking at this problem during your busy schedule. By looking at github, I found that when I initialize the database, I cannot connect to the database, but my database can be connected locally and remotely. So I would like to ask where there are more detailed documents to provide the system is centos7.4 system, docker is 1.13.1

**Comment by kfdm** [comment]
At it's core, Promgen is a basic django application so you should be able to use basic django-admin commands to help diagnose it.

For example `promgen diffsettings` would show you if Promgen is reading the database connection information from the environment or `promgen dbshell` would show if Promgen can connect

https://docs.djangoproject.com/en/2.2/ref/django-admin/#diffsettings
https://docs.djangoproject.com/en/2.2/ref/django-admin/#dbshell

**Comment by peixiaoqing** [comment]
Hello, the database connection problem has been resolved. Now my environment is: promgen on one server; prometheus and alertmanager on another server. When I use the command docker run --rm -p 8000: 8000 -v ~ / .config / promgen: / etc / promgen / line / promgen to start, I get an error that I cannot connect to alertmanager. Where can I find the configuration file to modify the connection?
![image](https://user-images.githubusercontent.com/35130532/72400563-a31cb600-3784-11ea-990c-6b3376b01eef.png)

**Comment by peixiaoqing** [comment]
> Promgen的核心是一个基本的django应用程序，因此您应该能够使用基本的django-admin命令来帮助对其进行诊断。
> 
> 例如，`promgen diffsettings`将显示Promgen是否正在从环境中读取数据库连接信息，或者`promgen dbshell`显示Promgen是否可以连接
> 
> [https://docs.djangoproject.com/zh-CN/2.2/ref/django-admin/#diffsettings ](https://docs.djangoproject.com/en/2.2/ref/django-admin/#diffsettings)
> [https://docs.djangoproject.com/zh-CN/2.2/ref/django-admin/#dbshel​​l](https://docs.djangoproject.com/en/2.2/ref/django-admin/#dbshell)

Hello, thank you for answering, the database problem has been resolved. My current environment is like this, prometheus + alertmanager is on one server, and promgen is on another server, but I found that the prometheus.yml and promgen.yml configuration files need to specify a local directory file. At this time, I have this directory file How do I specify it?
prometheus.yml at 192.168.8.105
![image](https://user-images.githubusercontent.com/35130532/72488446-f3128000-384b-11ea-887a-0d6efbd85a45.png)
promgen.yml at 192.68.8.109
![image](https://user-images.githubusercontent.com/35130532/72488518-25bc7880-384c-11ea-8b8e-bdf4071044dd.png)

**Comment by kfdm** [comment]
You would need a promgen worker running on the same node as your Prometheus node, and a shared volume for the files to be saved to
https://promgen.readthedocs.io/en/latest/conf/prometheus.html
