### ISSUE TITLE
Worker errror on docker run  

### ISSUE THREAD

**Issue by guiguemolla** [line/promgen#255]
I was following the steps of promgen installation and in the worker section I found this error at making the "docker run --rm -v ~/.config/promgen:/etc/promgen/ -v /etc/prometheus:/etc/prometheus line/promgen worker"

consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: 

Any thoughts? I checked the promgen files and everything seems fine

Thank you in advance

**Comment by guiguemolla** [comment]
I'm just stupid I did not choose the correct directory I'm so sorry

**Comment by kfdm** [comment]
No worries! If there is something that can be clearer about the documentation, let me know. 🙇

**Comment by guiguemolla** [comment]
Nono it was completely my fault in this case. I'm trying to work on preparing this service in docker swarm with automatic deploy so you are going to hear from me :smile:
