### ISSUE TITLE
Internal Error after installation

### ISSUE THREAD

**Issue by guiguemolla** [line/promgen#256]
Hi,
I followed all the steps in the promgem installation but the only thing the web shows me is:

"Internal Error!
You've encountered an error, please try again in some time or file an error report if the problem persists."

I do not have any errors in web or worker service. Is there any way to check where the error is comming from?

Thank you so much

**Comment by kfdm** [comment]
Internally, I tend to use http://sentry.io/ for error tracking, but you can also set `DEBUG=1` in your environment and then you should be able to see the detailed errors from Django

**Comment by guiguemolla** [comment]
I don't know if it because of this but I found that my worker and web cannot with the consumer

`[2020-03-17 13:21:24,130: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2020-03-17 13:21:26,145: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
`
This is the error I found but I double checked this url in the promegen configs and I dind't found any.
Any thoughts?

**Comment by kfdm** [comment]
Do you have a `CELERY_BROKER_URL` set in your environment? Example something like `redis://localhost:6379/0`

**Comment by guiguemolla** [comment]
Ahhh okay so then if you are using docker run the config volume does not work? Because in the documentation doesn't say to use enviroments.  I assumed that is passed by the config itself but not, you need the env variables. Right now I arrive to the login page, the problem is that de promgen user has no acces.
Any ideas?

**Comment by kfdm** [comment]
I'm a bit unsure which documentation page you're referring to, but any time you run a docker command, you typically need to pass the same environment information.
Sometimes, when it's annoying to pass everything around, I will run a one-off command in an existing container, to make things simpler. Something like `docker exec -it <containerid> promgen <some command`

**Comment by guiguemolla** [comment]
I'm using the readme in the repository. Is there another documentation?
Right now I'm trying to log in with promgen:promgen and it works but it says I do not have any permissions to the web but it is my super user.

**Comment by guiguemolla** [comment]
I've done it!. Now i need to do it in a docker swarm and not in my machine.
There's a question I ahve about this software. If I make a change in a service/rule in promgen if I connect to prometheus and check the config I'll see the change?

**Comment by guiguemolla** [comment]
Hi kfdm, I already moved the config to docker swarm and at least de web works and has no debug errors. I also have the worker running but when I try to commit I recieve a:
`monitoring-dev_web.1.uod6bp9vqxcy@devops-worker21    | [2020-03-25 10:58:53 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7)
monitoring-dev_web.1.uod6bp9vqxcy@devops-worker21    | [2020-03-25 10:58:53 +0000] [7] [INFO] Worker exiting (pid: 7)
monitoring-dev_web.1.uod6bp9vqxcy@devops-worker21    | [2020-03-25 10:58:53 +0000] [12] [INFO] Booting worker with pid: 12`

Do you know why is this happening? 
The service stills have the name worker and they are in the same network
Thank you so much

**Comment by guiguemolla** [comment]
Hi kfdm, I already moved the config to docker swarm and at least de web works and has no debug errors. I also have the worker running but when I try to commit I recieve a:

`[2020-03-25 10:58:53 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7) 
[2020-03-25 10:58:53 +0000] [7] [INFO] Worker exiting (pid: 7)
[2020-03-25 10:58:53 +0000] [12] [INFO] Booting worker with pid: 12`


Do you know why is this happening?
The service stills have the name worker and they are in the same network
Thank you so much

**Comment by kfdm** [comment]
I would check to see if it has all the same environment settings as your other containers.  It's difficult to tell what might be happening based on a single line of output.

Make sure that both the web instance and the worker instances can both connect to the same database and redis instances.

**Comment by guiguemolla** [comment]
I doble checked it and they are connected to it. I do not have more line errors. Those lines only appear when I press the commit button in the web.
Also i realised that only the worker needs the prometheus config (because of the volumes you use in docker-compose) is that correct right?

**Comment by zhenghanyin** [comment]
When I register a new rule,I had the same problem.

**Comment by zhenghanyin** [comment]
When I register a new rule,I had the same problem.Internal Error!
You've encountered an error, please try again in some time or file an error report if the problem persists.

**Comment by kfdm** [comment]
Have you tried running with `DEBUG=True` or something like Sentry, to see if that gives you additional information ?
One other thing to perhaps check is the path to promtool to see if Promgen can access it.

Example https://github.com/line/promgen/blob/cb5aff57883423f80ffb187ff4800e902b403665/promgen/tests/examples/promgen.yml#L6

**Comment by guiguemolla** [comment]
In the end I decide to not used it so I'll close the ticket.
Thank you so much
