### ISSUE TITLE
Promgen inside VM without docker

### ISSUE THREAD

**Issue by mr-joom** [line/promgen#26]
Is there any way to install promgen inside simple VM, without docker?

**Comment by kfdm** [comment]
Yes! You should be able to install it inside a normal, python virtual environment without any complicated setup. This is how I tend to do a lot of my development. If you deploy with uwsgi, you can use a similar config to this

```
[uwsgi]
plugins = python3
module = promgen.wsgi

http-socket = :8000 # or some other port number
master = true
processes = 2
buffer-size = 32768

virtualenv = /path/to/virtualenv
uid = <promgen user>
```

There's a few notes written in the README ( https://github.com/line/promgen#setting-up-promgen-for-development ) but let me know if you need me to clarify something :)
