### ISSUE TITLE
what is the username  and password?

### ISSUE THREAD

**Issue by or0or1** [line/promgen#27]
I  run promgen by  docker-compose.yaml.   But login  the  web,   what  is  username  and  password?

**Comment by kfdm** [comment]
Promgen is a fairly standard Django app, so by default there are no users created. You can create a new user from the CLI, using the Django [createsuperuser](https://docs.djangoproject.com/en/1.10/ref/django-admin/#django-admin-createsuperuser) command
`promgen createsuperuser`

**Comment by or0or1** [comment]
thanks very much

**Comment by kfdm** [comment]
You're welcome. I'll try to add that to the README to make things more clear :)

**Comment by or0or1** [comment]
@kfdm I meet a question。

for this command， I do not known  the password.
    promgen createsuperuser --username root --noinput --email  test@test.com

for this command, it will be wrong msg as following.
    promgen createsuperuser --username root  --email  test@test.com

Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.
Traceback (most recent call last):
  File "/usr/local/bin/promgen", line 11, in <module>
    load_entry_point('Promgen', 'console_scripts', 'promgen')()
  File "/usr/src/app/promgen/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 63, in execute
    return super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 183, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
TypeError: create_superuser() missing 1 required positional argument: 'email'

**Comment by kfdm** [comment]
This is the user that you want to create to login from the UI. It is separate from the linux users.
I typically run it once manually in a separate instance (instead of trying to run it through configuration management) 

I also tend to run it in 'interactive mode' as just `promgen createsuperuser` and let it prompt me for each value.

**Comment by or0or1** [comment]
@kfdm   
only run  promgen createsuperuser,the err msg as following. Maybe the reason for the docker.

Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.

**Comment by kfdm** [comment]
I don't remember the command exactly, but you should be able to run it as a 'one off' command with docker

```docker -it <containername> promgen createsuperuser```
* -i, --interactive                    Keep STDIN open even if not attached
* -t, --tty                            Allocate a pseudo-TTY

You will also want to pass the normal Volume and Environment flags to your container.

**Comment by or0or1** [comment]
@kfdm    you are right.    thanks.

docker exec -it  promgen_web_1  promgen createsuperuser

**Comment by kfdm** [comment]
Added some notes in 33d95c28c9f92cd242dca6467177ecd47e089da5 so I will close this now. Please feel free to open a new issue if you have additional questions.
