### ISSUE TITLE
Questions about usage.

### ISSUE THREAD

**Issue by fglaeser** [line/promgen#278]
Hi, a few questions about usage.
1. We have one prometheus for Production and one for Testing. What will be the best schema to handle this scenario? I've already created 2 shards, prod and test, and 1 service each, but a dont now if it is the best solution. Also the people that will be add projects to the prod or test services is different, so the test people don't need to see the prod service.
2. Is there a way to copy/clone project between services? Same scenario that before, two services, one for test and one for prod, after the project is ok in test, the idea is to copy (with out to remove from test) the project between services. Then do some changex to fix ip adresses, but the rules and the jobs arede same.
3. Can We integrate the authentication with our SSO Keycloak (OpenId)?

Thanks in advance.
Facundo

**Comment by fglaeser** [comment]
Hi, Forget about number 3. I've checked the documentation and is very straight forwards.
Thanks

**Comment by kfdm** [comment]
1. Yes I think having a release shard and testing shard are a valid use case. Here we are managing many more shards so I tend to have them broken up to release.example.com and beta.example.com and have separate Promgen instances.

As for controlling what users can see or not see, currently that is not possible but it's something I would like to address in the future.

2. You can typically export a list of targets (or rules) from any service/project and then import it back into Promgen `https://promgen.example.com/import` (This is listed under `Import Config` under the Misc menu). I often use this in my own development to pull a list of configurations from my Release environment into my Alpha Testing environment.

3. Yeah, there are some parts of the documentation that are lacking, so glad you figured it out 🙇

**Comment by fglaeser** [comment]
Thanks for the clarification
Best Regards
Facundo
