### ISSUE TITLE
the web  operation do not take effect

### ISSUE THREAD

**Issue by or0or1** [line/promgen#28]
The  err msg is  the followning. 

worker_1        | [2017-09-14 09:47:18,643: INFO/MainProcess] Received task: promgen.prometheus.write_config[21b64bc9-a37e-4fac-a03f-777a6cd2e17f]  
worker_1        | [2017-09-14 09:47:18,647: ERROR/ForkPoolWorker-1] Task promgen.prometheus.write_config[21b64bc9-a37e-4fac-a03f-777a6cd2e17f] raised unexpected: PermissionError(13, 'Permission denied')
worker_1        | Traceback (most recent call last):
worker_1        |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 367, in trace_task
worker_1        |     R = retval = fun(*args, **kwargs)
worker_1        |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 622, in __protected_call__
worker_1        |     return self.run(*args, **kwargs)
worker_1        |   File "/usr/src/app/promgen/prometheus.py", line 130, in write_config
worker_1        |     with atomic_write(path, overwrite=True) as fp:
worker_1        |   File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
worker_1        |     return next(self.gen)
worker_1        |   File "/usr/local/lib/python3.5/site-packages/atomicwrites/__init__.py", line 149, in _open
worker_1        |     with get_fileobject() as f:
worker_1        |   File "/usr/local/lib/python3.5/site-packages/atomicwrites/__init__.py", line 166, in get_fileobject
worker_1        |     delete=False, **kwargs)
worker_1        |   File "/usr/local/lib/python3.5/tempfile.py", line 549, in NamedTemporaryFile
worker_1        |     (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
worker_1        |   File "/usr/local/lib/python3.5/tempfile.py", line 260, in _mkstemp_inner
worker_1        |     fd = _os.open(file, flags, 0o600)
worker_1        | PermissionError: [Errno 13] Permission denied: '/etc/prometheus/tmpluryoyb_'

**Comment by or0or1** [comment]
my docker-compose.yaml is as following

version: '2'
services:
  base:
    build: .
    image: promgen
    network_mode: bridge
    command: sh -c "promgen migrate && promgen register docker-demo localhost 9090"
    #external_links:
    #  - mysql
    #  - redis
    environment:
      CELERY_BROKER_URL: redis://192.168.1.77:6379/0
      DATABASE_URL: mysql://promgen:promgen@192.168.1.77:3307/pypromgen
      SECRET_KEY: asdf

  web:
    extends: base
    command: promgen runserver 0.0.0.0:8000
    ports:
      - "192.168.1.228:8088:8000"
    environment:
      DEBUG: 1

  worker:
    extends: base
    command: worker -l info --queues localhost,celery
    links:
      - prometheus
    volumes:
      - ./docker:/etc/prometheus:rw

  prometheus:
    image: prom/prometheus
    network_mode: bridge
    links:
      - alertmanager
      - blackbox
    ports:
      - "9090:9090"
    volumes:
      - ./docker:/etc/prometheus:rw

  blackbox:
    image: prom/blackbox-exporter
    network_mode: bridge
    volumes:
      - ./docker:/etc/prometheus:rw

  alertmanager:
    image: prom/alertmanager
    command: -config.file=/etc/prometheus/alertmanager.yml
    network_mode: bridge
    links:
      - web
    ports:
      - "9093:9093"
    volumes:
      - ./docker:/etc/prometheus:rw

**Comment by or0or1** [comment]
when i commit  chmod a+rw ./docker, the permission problem has sloved。 But Prometheus still has not data。

although， promgen.json is ok。

#cat docker/promgen.json 
[
  {
    "labels": {
      "__farm_source": "promgen",
      "__shard": "Default",
      "farm": "default",
      "job": "nginx",
      "project": "test",
      "service": "Default"
    },
    "targets": [
      "192.168.1.121:9113"
    ]
  },
  {
    "labels": {
      "__farm_source": "promgen",
      "__shard": "Default",
      "farm": "\u4f5b\u5c71\u673a\u623f",
      "job": "node",
      "project": "192.168.1.178",
      "service": "Default"
    },
    "targets": [
      "192.168.1.12:9100",
      "192.168.1.123:9100",
      "192.168.1.86:9100"
    ]
  }

**Comment by kfdm** [comment]
I made two minor edits to your posts to add the backtick character to format it to be easier to ready :)

Hmm. I am admittedly not very knowledgable about docker, so I'm a bit unsure why Prometheus would not be able to read the file. Does anything show up in Prometheus' logs ? What does your Prometheus configuration file look like ?

**Comment by or0or1** [comment]
'''
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    cluster_name: 'promgen'

rule_files:
- "/etc/prometheus/promgen.rule"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.1.228:9093

scrape_configs:
  - job_name: 'promgen'
    file_sd_configs:
      - files:
        - "/etc/prometheus/promgen.json"
        refresh_interval: 15s

    relabel_configs:
    - source_labels: [__shard]
      regex: docker-demo
      action: keep

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - "/etc/prometheus/blackbox.json"
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackbox:9115  # Blackbox exporter.
      - source_labels: [__shard]
        regex: docker-demo
        action: keep
'''

similar with https://github.com/line/promgen/blob/master/docker/prometheus.yml

**Comment by kfdm** [comment]
Ahhhhh, I wonder if this is the case.
It's poor documentation on my part, but the name of your shard in Promgen, in this case "Default"  needs to match the shard in your relabel_config "docker-demo".

So you should either rename the Shard in Promgen, or rename the shard in your relabel_config.

This is not very obvious (and I needed to look at the config a few times myself) so I should provide better documentation around this ^^;

**Comment by or0or1** [comment]
@kfdm thank you very much。
