### ISSUE TITLE
Commit button not working

### ISSUE THREAD

**Issue by matheusroleal** [line/promgen#291]
When I try to use the commit button at promgen web UI instance, it does not reload my prometheus targets. I've set my `PROMGEN_CONFIG_DIR` to the right path. 

Is there any other configuration that is needed  to be done in order to this feature to work?

**Comment by kfdm** [comment]
While it is not labeled very well, the commit button is partly for dev use to submit a job to celery to update the remote workers. Are you using Promgen with celery workers?

**Comment by matheusroleal** [comment]
Yes. In my procfile I added a worker and a web instance:

```
web: gunicorn -b 0.0.0.0:$PORT  promgen.wsgi:application
worker: celery worker -A promgen --loglevel=INFO
```

**Comment by matheusroleal** [comment]
The mistake was mine... I was forgetting to set the `task_queue` for my celery worker 

```
web: gunicorn -b 0.0.0.0:$PORT  promgen.wsgi:application
worker: celery worker -A promgen -l info -Q localhost
```
