### ISSUE TITLE
run docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen bootstrap  the system recommend  1146, "Table 'prome.promgen_shard' doesn't exist"

### ISSUE THREAD

**Issue by liublcom** [line/promgen#302]
hi:
i have run the command docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen bootstrap,
then i put the mysql driver mysql://prome:Prome2020@10.0.184.106/prome when the system recommend to put DATABASE_URL,the last the system have this error :Running django system checks
Running django system checks
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'prome.promgen_shard' doesn't exist")

i found the database prome  don't have any table 。

i have do as followers
mkdir -p ~/.config/promgen
chmod 777 ~/.config/promgen
docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen bootstrap

**Comment by kfdm** [comment]
Hi @liublcom 
I think we can keep it all in a single issue, so probably no need to have #301 and #300 

As you have noticed (and I have also conincidentally noticed this week) there's a bit of a weird interaction in the `promgen bootstrap` command. The first time fails because it has some of the django defaults cached, but then it passes the second time. I'm working with my team to decide the best way to handle it, but it may involve splitting the command into two parts. I'm sorry for the confusion 🙇

**Comment by liublcom** [comment]
@kfdm ：
      #301 and #300  is not need to care.
     MySQLdb._exceptions.ProgrammingError: (1146, "Table 'prome.promgen_shard' doesn't exist") ,this message tell me we should first to init the database.

**Comment by liublcom** [comment]
@kfdm 
         excuse ，Are you following this issue。

**Comment by kfdm** [comment]
Can you try running `promgen migrate` ?
Sorry for this falling through the cracks. I'm trying to sort though backlog from winter break.

**Comment by mitspieler** [comment]
Same problem without docker-compose. Trying to run promgen migrate gives me the same error.  
> django.db.utils.ProgrammingError: (1146, "Table 'promgen.django_site' doesn't exist")
Bootstrap is working, it seems migrate is able to connect to mysql but won't init the database.

**Comment by kfdm** [comment]
Promgen currently doesn't create the database, only populates the tables. Does the database already exist?

**Comment by oxydedefer** [comment]
Any news about this issue ?

**Comment by ranqiwei** [comment]
> Same problem without docker-compose. Trying to run promgen migrate gives me the same error.
> 
> > django.db.utils.ProgrammingError: (1146, "Table 'promgen.django_site' doesn't exist")
> 
> Bootstrap is working, it seems migrate is able to connect to mysql but won't init the database.

I encountered the same matter as you.
