### ISSUE TITLE
it can work

### ISSUE THREAD

**Issue by KM612** [line/promgen#320]
Hi, I have deploy promgen in my mac(docker) by read the readme, but it not work ,I can see the web. I want to know why

**Comment by KM612** [comment]
the web is ok ,but the worker can not work

**Comment by kfdm** [comment]
Before we can help you, I think we're going to need more information about what you tried. Can you paste some of the commands you've run, and the output that you're seeing?

**Comment by KM612** [comment]
thank you for your reply, I have solve the problem by get the source code and run.  I think the problem caused by  the docker image , it maybe too old get from the  docker register.
