### ISSUE TITLE
docker-compose setup results in broken UI

### ISSUE THREAD

**Issue by ackstorm23** [line/promgen#351]
I installed promgen via the docker-compose.yml provided in the repository

While it appeared to complete successfully and is not throwing any errors in the logs when i try to access the website, it looks like this:

[screenshot](https://imgur.com/a/arS7si9)

What could be wrong?

**Comment by kfdm** [comment]
My guess is that last time I updated Django, I also needed to update whitenoise so that it serves the assets correctly. This PR should fix things 🙇

**Comment by kfdm** [comment]
Merged the update and it seems to work for me. Sorry for the trouble 🙇

**Comment by ackstorm23** [comment]
All better now, thanks!
