### ISSUE TITLE
[Request] Promgen Tutorial

### ISSUE THREAD

**Issue by hmmxp** [line/promgen#36]
Dear Developer,

Can provide a simple tutorial on how to use promgen? 
Also How Can We Configure Promgen When Prometheus is on a different server from Promgen?

**Comment by kfdm** [comment]
You're right. While I think I have mostly documented the installation steps, there is not a lot of information on how to use Promgen itself

While it could use more detail, it's mentioned on some of the docker instructions regarding a worker node

```
# Run Promgen web worker. This is typically balanced behind an NGINX instance
docker run --rm -p 8000:8000 -v ~/.config/promgen:/etc/promgen/ line/promgen:master

# Run Promgen celery worker. Make sure to run it on the same machine as your Prometheus server to manage the config settings
docker run --rm -v ~/.config/promgen:/etc/promgen/ -v /etc/prometheus:/etc/prometheus line/promgen:master worker
```

I will see what I can do to explain things better. Sorry for the delays.

**Comment by hmmxp** [comment]
Dear Paul,

Hopeful more tutorial will be out as it will be beneficial as i have around
10 Prometheus server spread across multiple location and Promgen looks like
a good solution to manage the environment

**Comment by hmmxp** [comment]
# Run Promgen web worker. This is typically balanced behind an NGINX instance
docker run --rm -p 8000:8000 -v ~/.config/promgen:/etc/promgen/ line/promgen:master

# Run Promgen celery worker. Make sure to run it on the same machine as your Prometheus server to manage the config settings
docker run --rm -v ~/.config/promgen:/etc/promgen/ -v /etc/prometheus:/etc/prometheus line/promgen:master worker

Correct me if i am wrong

1. I need to have a central promgen server
2. For every prometheus server or server running the prometheus exporter, i need to have both promgen web worker and celery worker running?

**Comment by kfdm** [comment]
You can have your Promgen web worker running anywhere you want and then you need a single worker for each Prometheus instance. I'm going to try to update the documentation around that this week.

**Comment by hmmxp** [comment]
Dear Paul,

Thank you for the feedback, will await your documentation and see how to finish configuring my promgen stack as i am not sure how to manage my multiple Prometheus server with promgen
