### ISSUE TITLE
promgen compose

### ISSUE THREAD

**Issue by Tommassino** [line/promgen#41]
Hi,

promgen looks exactly what i need to run prometheus since I want to change the configurations of alerts and nodes dynamically. I've started with taking your docker-compose that you have in your project and altering it to include both the mysql and redis databases (later on I can move them outside of this docker). I can successfully start the docker containers and all of them seem to be running just fine, but I'm having issues configuring promgen.

I add a exporter successfully to the UI and the test functionality confirms it working, however the Prometheus server does not get it added to its targets. Further when I attempt to add a alert rule i get internal server errors (and nothing visible in the promgen log). What am I doing wrong?

PS: i ran the DB initialization scripts manually (i plan to run them automatically later).

![image](https://user-images.githubusercontent.com/698950/35500060-56ac0692-04d5-11e8-98f1-10bf3195e67d.png)

The prometheus server has been added:

![image](https://user-images.githubusercontent.com/698950/35500208-f2fea5ae-04d5-11e8-8fcb-d3b8f17a96a0.png)

The compose (WIP) used:

```
version: '2'
services:
  redis:
    image: redis
    container_name: redis
    network_mode: bridge
    restart: always
    ports:
      - 6379:6379

  mysql:
    image: mariadb
    container_name: mysql
    network_mode: bridge
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pypromgen
      MYSQL_USER: promgen
      MYSQL_PASSWORD: promgen

  base:
    build: .
    image: promgen
    network_mode: bridge
    command: echo ""
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: mysql://promgen:promgen@mysql:3306/pypromgen
      SECRET_KEY: asdf

  prep:
    extends: base
    container_name: prep
    command:  sh -c "promgen migrate"
    links:
      - mysql
      - redis
    environment:
      DEBUG: 1

  web:
    extends: base
    container_name: web
    command: promgen runserver 0.0.0.0:8000
    links:
      - mysql
      - redis
      - prep
      - nodeexporter
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1

  worker:
    extends: base
    container_name: worker
    command: worker -l info --queues localhost,celery
    links:
      - prometheus
      - redis
    volumes:
      - ./docker:/etc/prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: bridge
    links:
      - alertmanager
      - blackbox
    ports:
      - "9090:9090"
    volumes:
      - ./docker:/etc/prometheus

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    network_mode: bridge
    volumes:
      - ./docker:/etc/prometheus

  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    network_mode: bridge
    ports:
      - 9100:9100

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    network_mode: bridge
    links:
      - web
    ports:
      - "9093:9093"
    volumes:
      - ./docker/alertmanager.yml:/etc/alertmanager/config.yml
```

**Comment by kfdm** [comment]
Ah, this looks like partly a bug with my sample files and partly a bug with my poor documentation :(

If you look at the example Prometheus configuration file there is this block

```yaml
scrape_configs:
  - job_name: 'promgen'
    file_sd_configs:
      - files:
        - "/etc/prometheus/promgen.json"
    relabel_configs:
    - source_labels: [__shard]
      regex: docker-demo
      action: keep
```

The regex for "docker-demo" needs to match the name of the shard which actually defaults to "Default". There are a few options

1. Change the config to "regex: Default"
2. Change the shard name from Promgen to "docker-demo"
3. Delete the "relabel_configs" block under scrape_configs

I'll see if I can fix up the example files and documentation. Sorry for the confusion.

**Comment by Tommassino** [comment]
Thanks for the quick reply. I went into the prometheus docker and checked whether promgen writes anything to /etc/prometheus/promgen.json and that file seems to be missing. Maybe I made some mistake with the database configurations and the information isn't being fetched by the worker?

**Comment by kfdm** [comment]
I imagine if it was a database config issue, then there would be a more visible error. If you run the cli, does anything get output? (about to head home for the day so I don't recall the docker command exactly)

```bash
promgen targets # Print out Prometheus targets
promgen rules  #print out rules
```

**Comment by Tommassino** [comment]
```
docker exec -it worker /bin/bash

> promgen targets
```
gives me breadcrumbs and

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-2)")
```
Ill look into the database configuration.

**Comment by Tommassino** [comment]
updated the docker file to include the mysql link for the worker
```
ubuntu@ip-172-31-38-136:~/promgen$ docker exec -it worker /bin/bash
bash-4.3$ promgen targets
[
  {
    "labels": {
      "__farm_source": "promgen",
      "__shard": "Default",
      "farm": "Farm",
      "job": "node",
      "project": "Project",
      "service": "Default"
    },
    "targets": [
      "nodeexporter:9100"
    ]
  }
]
bash-4.3$ promgen rules
Traceback (most recent call last):
  File "/usr/local/bin/promgen", line 11, in <module>
    load_entry_point('Promgen', 'console_scripts', 'promgen')()
  File "/usr/src/app/promgen/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/promgen/management/commands/rules.py", line 35, in handle
    self.stdout.write(prometheus.render_rules(version=kwargs['version']))
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 107, in write
    if ending and not msg.endswith(ending):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by seoester** [comment]
Your problems with generating the rules file may be related to #39.

**Comment by Tommassino** [comment]
Thanks for the suggestion, I applied the changeset in that patch, yet it does not seem to help. 

I added logging to file in the settings.py (if sentry isnt configured) and got these errors in the log:

[debug.log](https://github.com/line/promgen/files/1673428/debug.log)

The main thing that seems to be the issue is:

```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/promtool'
```

**Comment by seoester** [comment]
My bad, that actually is #38.

However, it has been merged, so you should be able to pull the new version of the image.

**Comment by Tommassino** [comment]
I got to the point where I actually see rules rendered in the UI and can add/edit them etc. However it seems prometheus does not register an update. When i look at the file in the prometheus docker:

```$ docker exec prometheus cat /etc/prometheus/promgen.rule
groups:
- name: Default » Default » Project
  rules:
  - alert: UAAAAAAAAAAAAAAAAAAA
    annotations:
      rule: http://example.com/rule/1/edit
    expr: node_load1 > 2
    for: 30s
    labels:
      project: Project
```

It does display the new rule file, however only when I update it manually (i have to specify the path) via:

`docker exec web promgen rules --reload /etc/prometheus/promgen.rule`

I checked the promgen.yml config file (the rule file points to /etc/prometheus/promgen.rule) so Im not sure whats wrong at this point. The functionality is there, but somehow some configuration is messing something somewhere up.

**Comment by seoester** [comment]
This seems like a similar error as #39: The return of `render_rules` is treated as `str`, although it is of type `bytes`. You could patch the line 35 in `promgen/management/commands/rules.py"` to convert the returned value.

I don't understand what went wrong yet. If the rules files is correctly written but the rules are not showing up in prometheus, check if the prometheus configuration points to the correct rules file.

**Comment by Tommassino** [comment]
> I don't understand what went wrong yet. If the rules files is correctly written but the rules are not showing up in prometheus, check if the prometheus configuration points to the correct rules file.

Nono, maybe I wasnt clear:

> It does display the new rule file, however only when I update it manually (i have to specify the path) via:

It updates the rule file only when i update it manually.

I found a workaround for now at least, when i removed the `CELERY_BROKER_URL: redis://redis:6379/0` variable to let promgen to fallback to not using redis it started working.

**Comment by seoester** [comment]
Thanks for specifying.

You didn't post how you bootstrap your setup, but you may be missing some worker queue configuration:

The worker must subscribe to a queue (`-l` flag) with the hostname of the prometheus instance you registered with `promgen register …`.

**Comment by kfdm** [comment]
@Tommassino @seoester thank you a lot for your help so far trying to figure things out. Looks like I need to do some work on the installation instructions to make things more clear ^^;

**Comment by kfdm** [comment]
@Tommassino I made some changes in #44 which I think will explain things a bit better and work a bit better. Can you take a look and tell me what you think? This should also take into account the changes @seoester did to include promtool into the same image.

**Comment by Tommassino** [comment]
Hey, I consider this issue closed.
