### ISSUE TITLE
Issues updating promgen version to 0.60.0 on Centos7

### ISSUE THREAD

**Issue by mysterious-maniac** [line/promgen#483]
Hi all,

Looking to update our promgen from 0.46 -> latest 0.60.

A major difference I found is that recent versions are using python3.9, so it has been installed onto the Centos7 box.

However, when following the readme, docker-compose-bootstrap outputs the following message continuously:
```
# docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen docker-compose-bootstrap
Waiting for database to startup
Waiting for database to startup
Waiting for database to startup
```

I've pulled the latest docker image and ~/.config/promgen/ has the same configuration files like we have on our 0.46. Is there something else I should be doing differently when upgrading between versions?

Thanks.

**Comment by kfdm** [comment]
I don't have a lot of time to debug this right now, but here are a few quick thoughts.

`docker-compose-bootstrap` is mostly just to have a simple docker-compose demo. Typically you wouldn't need to run that again for just an update.

`docker-compose-bootstrap` basically runs `until promgen check 2>/dev/null` in a loop, to check the database connection before continuing. I would check your database settings (Check `DATABASE_URL` environment variable)


Upgrades should generally just be

1. Pull and run new image
2. Run `docker exec -it <container image> promgen migrate` to update database

**Comment by mysterious-maniac** [comment]
Thanks for the response, @kfdm!

The command to update the database after the new image is pulled and run works flawlessly. I think the upgrade instructions should be added somewhere in the README.

I still have issues with the python3.9 versions (0.58+), but will submit another issue for that.
