### ISSUE TITLE
 怎么定义prometheus规则 How to define the Prometheus rule

### ISSUE THREAD

**Issue by peixiaoqing** [line/promgen#49]
HI  developer：
When I use the test rules, the backstage is wrong, 500, how do you solve it in general? How do you use promgen to generate Prometheus rules?
![qq 20180131134955](https://user-images.githubusercontent.com/35130532/35607275-4a1e4d8a-068e-11e8-923b-b91719195e49.png)

**Comment by Tommassino** [comment]
May be related to https://github.com/line/promgen/pull/39 
Try running the command `promgen targets`

**Comment by peixiaoqing** [comment]
Thanks to the developers to reply to the news in their busy schedule
According to the command to my reply "promgen targets" tried to create the rules, the background or the 500 false, I can see the bottom of the screenshot.
Now I say the way I install it, I install it according to the installation of centos7, and do not use docker. After the installation is complete, I add the host and monitor port, test can pass, but when adding rules, place error 500 rules: node_load1{project= 34, <exclude>} > 5 is my rule is wrong, which is wrong, please help out, thank you。
![aa](https://user-images.githubusercontent.com/35130532/35657785-44e2fad6-0739-11e8-9da3-a8abf90e36d6.png)
![bb](https://user-images.githubusercontent.com/35130532/35657792-4a6478c2-0739-11e8-9baf-a45843181f7e.png)
![cc](https://user-images.githubusercontent.com/35130532/35657827-7e7984c2-0739-11e8-9d2e-85287ebd3869.png)
![dd](https://user-images.githubusercontent.com/35130532/35657832-8105932a-0739-11e8-9309-ce40c097afe0.png)

**Comment by kfdm** [comment]
The rule tester is still probably a bit rough. If you go into the Promgen Admin and look at the Shard list ( /admin/promgen/shard/ ) find the shard you're using and ensure "Proxy" is checked.

That whole section is poorly documented so I need to fix that. Sorry for the confusion :(

**Comment by peixiaoqing** [comment]
Hello developer: according to the tips given to me above, I don't see very well. Can you give me a document on the definition of the rules? Thank you

**Comment by peixiaoqing** [comment]
Hello developer: according to the tips given to me above, I understand very well. Can you give me a document on the definition of the rules? Thank you

**Comment by peixiaoqing** [comment]
Hello developer: according to my tips above, I don't understand very well. Can you give me a document on the definition of the rules? Thank you

**Comment by kfdm** [comment]
I believe it may be an issue with the default settings for Promgen's default shard settings but I need to take a look. I was on a business trip today so I will try to look at it tomorrow.

**Comment by peixiaoqing** [comment]
Thank you，Dear developer

**Comment by xavierzip** [comment]
@kfdm  Sorry to come back to this old thread again. Do you mind to share some ideas about the concept of "Shard"? Can also point me to existing explanation if there is any. Thank you very much!

**Comment by kfdm** [comment]
From Promgen's perspective, *shard* is a collection of Prometheus servers, scraping the same targets. For example, here, we typically have 2 prometheus servers assigned to each shard for high availability reasons. We have several shards that are shared across several teams and a few "dedicated" shards for specific teams that have a large number of services to monitor

Example.
Shard A (prom-001, prom002)
- Team1 (or just a Service in Promgen)
- Team2
- Team3
Shard B (prom-003, prom-004)
- Team4

**Comment by saravana-code** [comment]
@kfdm may i know the equivalent "promgen targets" command for promgen version 
promgen --version
2.2.13

we have tried adding the prometheus running as docker in same host where promgen running as docker, tried adding external prometheus,alertmanager, but we are not able to retrieve current alerts in any of our alert manager and also we are not able to update the rules created on promgen UI to respective alertmanagers/prometheus.

http://ourIP:8080/api/v1/targets returns empty braces, can you direct us on what needs to be correct to get it working?

[
  {
    "labels": {
      "__farm_source": "promgen",
      "__scheme__": "http",
      "__shard": "docker-demo",
      "farm": "prom-host",
      "job": "app",
      "project": "new-project",
      "service": "prometheus"
    },
    "targets": []
  }
]

can you please help?

**Comment by kfdm** [comment]
@saravana-code it would be better to open up a new issue. I will close this and copy it over 🙇
