### ISSUE TITLE
Validation of redis URL fails during bootstrap

### ISSUE THREAD

**Issue by seoester** [line/promgen#51]
Validation of redis URLs such as `redis://redis:6379/0` (i.e. without a tld part) fails during bootstrap process with the error: `Enter a valid URL.`
When using docker this URL will often lack a tld part.

The root cause is the Django [`URLValidator`](https://docs.djangoproject.com/en/2.0/ref/validators/#urlvalidator) utility.
It seems to be directed more at end user input on a web page than for validating admin input.

[Ticket #25418](https://code.djangoproject.com/ticket/25418) tracks progress on the topic in the Django Project. [Ticket #9202](https://code.djangoproject.com/ticket/9202) is also related.

I would suggest either removing validation or replacing it with something more meaningful, for example a simple RegEx or an actual check which tests whether the URL's target is reachable.

What are your thoughts on the subject?

**Comment by kfdm** [comment]
Hmm, that's annoying :(
Perhaps can try to use urllib.parse.urlparse as a sanity check for syntax. I think testing if the URL is reachable may be slightly more difficult since I typically don't access redis directly (I leave that to celery)

**Comment by kfdm** [comment]
Hmm. Was trying to test this today and I seem to be having difficulty reproducing it.
Right now Promgen is using Django 1.11.x and it seems to validate fine. 

```
docker run -i --rm promgen:tmp bootstrap 
/usr/src/app/promgen/settings.py:220: UserWarning: Unset SECRET_KEY setting to random for now
  warnings.warn('Unset SECRET_KEY setting to random for now')
Bootstrapping Promgen
Creating config directory /home/promgen/.config/promgen 
Creating promgen config /home/promgen/.config/promgen/promgen.yml from /usr/src/app/promgen/tests/examples/promgen.yml
Use ** for SECRET_KEY ? (yes/no) yes
Writing ** to /home/promgen/.config/promgen/SECRET_KEY
Please enter a value for DATABASE_URL: mysql://promgen:promgen@127.0.0.1/promgen
Writing mysql://promgen:promgen@127.0.0.1/promgen to /home/promgen/.config/promgen/DATABASE_URL
Please enter a value for CELERY_BROKER_URL: redis://localhost:6379/0
Writing redis://localhost:6379/0 to /home/promgen/.config/promgen/CELERY_BROKER_URL
```

**Comment by seoester** [comment]
Actually `localhost` is the one hard-coded exception (see `host_re` in the [source code](https://docs.djangoproject.com/en/2.0/_modules/django/core/validators/#URLValidator))...

Other URLs without a tld, e.g. `redis://redis:6379/0` will fail.

**Comment by kfdm** [comment]
Ok, now I see it! Lets see how to fix it now :)

**Comment by kfdm** [comment]
Probably can do something like this but I'll test a little bit more to make sure it works as expected

```diff
diff --git a/promgen/management/commands/bootstrap.py b/promgen/management/commands/bootstrap.py
index 84c7030..83dbd01 100644
--- a/promgen/management/commands/bootstrap.py
+++ b/promgen/management/commands/bootstrap.py
@@ -3,6 +3,7 @@
 
 import os
 import shutil
+from urllib.parse import urlparse
 
 import dj_database_url
 from django.conf import settings
@@ -57,4 +58,4 @@ class Command(BaseCommand):
         self.write_setting('DATABASE_URL', test=dj_database_url.parse)
         # Schemes based on list of supported brokers
         # http://docs.celeryproject.org/en/latest/getting-started/brokers/index.html
-        self.write_setting('CELERY_BROKER_URL', test=URLValidator(schemes=['redis', 'amqp', 'sqs']))
+        self.write_setting('CELERY_BROKER_URL', test=urlparse)
```

**Comment by seoester** [comment]
The urlparse utility is quite lenient, it doesn't check for much.
Some ideas for testing the parsed URL:

 * `scheme` is non-empty / is equal to one of the supported three
 * For redis and amqp: `netloc` is non-empty
 * For redis: `path` is empty (?) or an int
 * For amqp: `path` is not empty
 * For sqs: `username` and `password` are non-empty

Celery supports additional schemes but having these three seems like a good start.

**Comment by kfdm** [comment]
I had initially thought to just test that it wasn't a typo, but shouldn't be difficult to put in a bit more robust check :)

**Comment by nikita2206** [comment]
Why not just remove this validation completely? As OP said this validation is aimed at web user-input, not ops configuration. Would you accept a PR removing validation completely?

**Comment by kfdm** [comment]
You're right, I think it can probably just be removed.

**Comment by kfdm** [comment]
I hope to have a PR ready this week
