### ISSUE TITLE
Register Service with existing name

### ISSUE THREAD

**Issue by seoester** [line/promgen#53]
When trying to register a service with an already existing name the view crashes (500: Internal Server Error).

[traceback.txt](https://github.com/line/promgen/files/1691856/traceback.txt)

Steps to reproduce:

 1. Create shard: "Shard 1"
 2. Create shart: "Shard 2"
 3. Register service in "Shard 1" with name "Default Service"
 4. Register service in "Shard 2" with name "Default Service"

Interestingly this issue does not occur when creating projects with the same name. Here, an appropriate error message is displayed.

**Comment by kfdm** [comment]
Right now, Services and Projects are unique globally (should have a unique key on the database) because I need unique labels to route alerts. I would think that Project would fail in the same way. Hmm. I'll take a look on Monday.
