### ISSUE TITLE
Promgen Worker

### ISSUE THREAD

**Issue by hmmxp** [line/promgen#58]
Dear All,

Currently i have created an installation guide for Promgen Web on CentOS 7, how can i install and configure Promgen Worker On CentOS 7?

**Comment by seoester** [comment]
The preparation and installation required for the worker are the same as for the web app.

Then you register and start like this:

```sh
# Register prometheus server
# Syntax: promgen register <shard name> <prometheus host> <prometheus port>
promgen register default localhost 9090
# Start worker
# Syntax: celery -A promgen worker -l <log level> -Q <queues>
celery -A promgen worker -l info -Q localhost
```

The worker needs to subscribe to the queue with the host name of the prometheus server. 

You can also have a look at #57, it includes documentation on how to setup the web app and the worker using docker.

**Comment by hmmxp** [comment]
i believe the above is for push model if promgen and promethues is installed on the same server.

But my promethues and promgen is on different server, how can i configure pull model?

**Comment by kfdm** [comment]
The celery worker is installed the same way as the web app and as long as they can reach the same database and redis instance, it doesn't matter if the web app and workers are on different servers.

Apparently I forgot to merge some docs updates but you should be able to see some illustrations here
https://github.com/line/promgen/pull/46/files
I'll try to go through the PRs on Monday.

**Comment by hmmxp** [comment]
Dear Paul & Seoster,

Will await the documents and finish testing in my linux environment and if i have spare time will test on docker

thank you all for the wonderful job

**Comment by kfdm** [comment]
Correct. Those commands register the worker in Promgen's database so the data is saved between reboots and anything else :)

The worker flags you need to add to your startup command so that it knows which queue to run from.

**Comment by kfdm** [comment]
uWSGI would be used to run the Promgen worker, so there are no worker flags required.

Something like systemd or another process manager would run the worker on the same node as Prometheus. I use something like this when deployed from Ansible


```
[Unit]
Description=Daemon for Celery
After=network.target

[Service]
Type=simple
ExecStart={{ promgen_virutalenv }}/bin/celery -A promgen worker -l info --queues {{ ansible_host }}
Restart=on-failure
User=prometheus

[Install]
WantedBy=multi-user.target
```

**Comment by hmmxp** [comment]
Dear Paul,

Noted on this let me test it out and feedback and update the document as needed
