### ISSUE TITLE
Promgen user 

### ISSUE THREAD

**Issue by zhangjianweibj** [line/promgen#87]
hill，i run promgen by docker compose,and the project running seems normally.but do not know how to configure the dashboard.finding the project lack of a detailed user manual.can you supply more detail user manual or a detail configuration demo.very thanks

**Comment by kfdm** [comment]
Sorry for the delayed response.
It looks like the link at the top of the repo is not current, so perhaps https://promgen.readthedocs.io/en/latest/ is slightly more current documentation.
There are still likely many places where the documentation could be expanded though it may take me a bit of time to get to it.
